# Generated by Django 3.2 on 2023-01-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='birthdate',
            field=models.DateField(),
        ),
    ]
